# Generated by Django 4.2.5 on 2024-03-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField()),
                ('year', models.DateField()),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
