# Generated by Django 4.2.5 on 2024-03-01 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='discription',
            new_name='description',
        ),
    ]
