# Generated by Django 4.2.5 on 2024-03-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0003_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
