# Generated by Django 4.2.5 on 2024-03-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0004_alter_card_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='bg'),
        ),
    ]
