# Generated by Django 4.2.5 on 2024-03-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0005_card_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
